{% set name = "django-vite-plugin" %}
{% set version = "4.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_vite_plugin-{{ version }}.tar.gz
  sha256: 9ddeeb99ea7a81d747f410e6ff58a1671b054af4933fb91bde526096331568ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - django_vite_plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Vite build tools integration for django
  home: https://github.com/protibimbok/django-vite-plugin
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
